# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-25 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date', models.DateTimeField()),
                ('sex', models.CharField(choices=[('mal', '男'), ('female', '女')], default='男', max_length=2)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 't_user',
            },
        ),
    ]
